// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHVFiO6wW5hvlESLaqaXbhC50j_xMRiR8',
    appId: '1:279804006741:web:361158c839373cda705fdc',
    messagingSenderId: '279804006741',
    projectId: 'predemo-wsmb',
    authDomain: 'predemo-wsmb.firebaseapp.com',
    storageBucket: 'predemo-wsmb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANDCOdGI3CJU9V6UWv7xrux4FJKnhE4Jw',
    appId: '1:279804006741:android:043032d01028cb02705fdc',
    messagingSenderId: '279804006741',
    projectId: 'predemo-wsmb',
    storageBucket: 'predemo-wsmb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0JSm6Vfx_KuweEA5_cQCH_rJPfM8Swk',
    appId: '1:279804006741:ios:f64cb456abe28fd0705fdc',
    messagingSenderId: '279804006741',
    projectId: 'predemo-wsmb',
    storageBucket: 'predemo-wsmb.appspot.com',
    iosBundleId: 'com.example.kongsiKereta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm0JSm6Vfx_KuweEA5_cQCH_rJPfM8Swk',
    appId: '1:279804006741:ios:f64cb456abe28fd0705fdc',
    messagingSenderId: '279804006741',
    projectId: 'predemo-wsmb',
    storageBucket: 'predemo-wsmb.appspot.com',
    iosBundleId: 'com.example.kongsiKereta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHVFiO6wW5hvlESLaqaXbhC50j_xMRiR8',
    appId: '1:279804006741:web:e45dc38607ceda69705fdc',
    messagingSenderId: '279804006741',
    projectId: 'predemo-wsmb',
    authDomain: 'predemo-wsmb.firebaseapp.com',
    storageBucket: 'predemo-wsmb.appspot.com',
  );
}
